/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.clube;

/**
 *
 * @author Cesar
 */
public class App extends javax.swing.JFrame {
        Clube time1 = new Clube();
        Clube time2 = new Clube();
    /**
     * Creates new form CampanhaFutebol
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVitoria = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnDerrota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVitoria = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEmpate = new javax.swing.JLabel();
        lblDerrota = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        lblPontuacao = new javax.swing.JLabel();
        lblPontuacao2 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVitoria2 = new javax.swing.JLabel();
        btnVitoria2 = new javax.swing.JButton();
        btnRegistrar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblEmpate2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDerrota2 = new javax.swing.JLabel();
        btnDerrota2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnVitoria.setText("Registrar vitória");
        btnVitoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoriaActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar empate");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDerrota.setText("Registrar derrota");
        btnDerrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vitórias:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Empates:");

        lblVitoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVitoria.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Derrotas:");

        lblEmpate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpate.setText("0");

        lblDerrota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDerrota.setText("0");

        lblb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblb.setText("Pontuação: ");

        lblPontuacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPontuacao.setText("0 pontos");

        lblPontuacao2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPontuacao2.setText("0 pontos");

        label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label.setText("Pontuação: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Vitórias:");

        lblVitoria2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVitoria2.setText("0");

        btnVitoria2.setText("Registrar vitória");
        btnVitoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoria2ActionPerformed(evt);
            }
        });

        btnRegistrar2.setText("Registrar empate");
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Empates:");

        lblEmpate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpate2.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Derrotas:");

        lblDerrota2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDerrota2.setText("0");

        btnDerrota2.setText("Registrar derrota");
        btnDerrota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrota2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacao2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVitoria2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblVitoria2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmpate2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblDerrota2))
                            .addComponent(btnDerrota2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVitoria)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblVitoria)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmpate)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblDerrota))
                            .addComponent(btnDerrota))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitoria)
                    .addComponent(btnRegistrar)
                    .addComponent(btnDerrota))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblVitoria)
                    .addComponent(lblEmpate)
                    .addComponent(jLabel4)
                    .addComponent(lblDerrota))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblb)
                    .addComponent(lblPontuacao))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVitoria2)
                    .addComponent(btnRegistrar2)
                    .addComponent(btnDerrota2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lblVitoria2)
                    .addComponent(lblEmpate2)
                    .addComponent(jLabel6)
                    .addComponent(lblDerrota2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(lblPontuacao2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoriaActionPerformed
        time1.registrarVitoria();
        
        lblVitoria.setText(time1.getVitoria().toString());
        
        lblPontuacao.setText(String.format("%d pontos", time1.getPontuacao()));
    }//GEN-LAST:event_btnVitoriaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        time1.registrarEmpate();
        
        lblEmpate.setText(time1.getEmpate().toString());
        
        lblPontuacao.setText(String.format("%d pontos", time1.getPontuacao()));
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnDerrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrotaActionPerformed
        time1.registrarDerrota();
        
        lblDerrota.setText(time1.getDerrota().toString());
        
        lblPontuacao.setText(String.format("%d pontos", time1.getPontuacao()));
    }//GEN-LAST:event_btnDerrotaActionPerformed

    private void btnVitoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoria2ActionPerformed
        time2.registrarVitoria();
        
        lblVitoria2.setText(time2.getVitoria().toString());
        
        lblPontuacao2.setText(String.format("%d pontos", time2.getPontuacao()));
    }//GEN-LAST:event_btnVitoria2ActionPerformed

    private void btnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar2ActionPerformed
        time2.registrarEmpate();
        
        lblEmpate2.setText(time2.getEmpate().toString());
        
        lblPontuacao2.setText(String.format("%d pontos", time2.getPontuacao()));
    }//GEN-LAST:event_btnRegistrar2ActionPerformed

    private void btnDerrota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrota2ActionPerformed
        time2.registrarDerrota();
        
        lblDerrota2.setText(time2.getDerrota().toString());
        
        lblPontuacao2.setText(String.format("%d pontos", time2.getPontuacao()));
    }//GEN-LAST:event_btnDerrota2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerrota;
    private javax.swing.JButton btnDerrota2;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar2;
    private javax.swing.JButton btnVitoria;
    private javax.swing.JButton btnVitoria2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblDerrota;
    private javax.swing.JLabel lblDerrota2;
    private javax.swing.JLabel lblEmpate;
    private javax.swing.JLabel lblEmpate2;
    private javax.swing.JLabel lblPontuacao;
    private javax.swing.JLabel lblPontuacao2;
    private javax.swing.JLabel lblVitoria;
    private javax.swing.JLabel lblVitoria2;
    private javax.swing.JLabel lblb;
    // End of variables declaration//GEN-END:variables
}
